version: '3'

services:
  vaaniverse:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - INDICTRANS2_MODEL_DIR=./models/indictrans2
    volumes:
      - ./models:/app/models
    restart: unless-stopped
